#!/bin/bash

DropPod="/usr/local/DropPod"

command=$1
shift

export SSL_CERT_FILE=/usr/local/share/ca-bundle.crt

case "$command" in
  pod | pods )
    cat <(echo "include baseline::types") <(for pod; do /usr/bin/ruby -r open-uri -e "puts open('$pod').read"; done) | ${DropPod}/binstubs/puppet apply
    ;;
  test )
    cat <(echo "include baseline::types") <(for pod; do /usr/bin/ruby -r open-uri -e "puts open('$pod').read"; done) | ${DropPod}/binstubs/puppet apply --noop 2>&1 | grep '(noop)' -qc
    [[ $? -ne 0 ]]
    exit $?
    ;;
  module )
    ${DropPod}/binstubs/puppet module install "$@"
    ;;
  * )
    echo "Unrecognized command '${command}'"
    exit 1
esac

